#!/bin/bash
#
# Create the darwin bundle
#
set -e
assert_subshell() {
    # Subshells are strange with set -e so need to return $? after called to
    # test false at outershell.
    return $?
}

umask 027

if ! [[ $repo && $dest ]]; then
    echo "Usage: repo=<url> dest=<dir> $0" 1>&2
    exit 1
fi
export bundle_repo=$repo

# First channel is always develop
export bundle_channel=develop

export bundle_name=org.radtrack
export bundle_os_machine=darwin/x86_64
export bundle_support=support@radtrack.org
export bundle_version=$(date +%Y%m%d.%H%M%S)

src=$PWD

if [[ $dev_install ]]; then
    mkdir -p "$dest"
    _install() {
        for f in "$@"; do
            ln -s "$PWD/$f" "$dest"
        done
    }
    _install_rm() {
        _install "$@"
    }
else
    if [[ ! -d $dest ]]; then
        echo "$dest: destination directory doesn't exist" 1>&2
        exit 1
    fi
    _install() {
        install -m 0440 "$@" "$dest"
    }
    _install_rm() {
        _install "$@"
        rm "$@"
    }
fi

dest_bundle_root=$dest/$bundle_name
dest=$dest_bundle_root/$bundle_os_machine/$bundle_version
mkdir -p "$dest"
dest=$(cd "$dest"; pwd)

tgz=install.tar.gz
tar cz -T - -f "$tgz" <<'EOF'
darwin-radtrack.sh
install-darwin-pkg.sh
install-functions.sh
install-lock.sh
install-main.sh
install-update-daemon.sh
install-user.sh
remove-existing-vm.pl
update-daemon.sh
EOF
_install_rm "$tgz"

channel_dir=$(dirname "$dest")/$bundle_channel
channel_new=$channel_dir.new
channel_old=$channel_dir.old

export bundle_repo=${dest%$bundle_name}

for dmg in XQuartz VirtualBox Vagrant; do
    f=$dmg_src/$dmg.dmg
    if [[ ! -f $f ]]; then
        echo "$f: not found" 1>&2
        exit 1
    fi
    _install "$f"
done

(
    cd ..
    if [[ ! $no_container_build ]]; then
        container-conf/builder vagrant
    fi
    _install_rm radiasoft-radtrack.box
)
assert_subshell

for b in install.sh update.sh; do
    n=$dest/$b
    perl -p - "$b" <<'EOF' > "$n"
s{BUNDLE_NAME}{$bundle_name}g;
s{CHANNEL}{$bundle_channel}g;
s{OS_MACHINE}{$bundle_os_machine}g;
s{REPO}{$bundle_repo}g;
s{SUPPORT}{$bundle_support}g;
s{VERSION}{$bundle_version}g;
EOF
    chmod 440 "$n"
done

(
    cd "$dest"
    f="$src/MANIFEST"
    ls > "$f"
    _install_rm "$f"
)
assert_subshell

rm -rf "$channel_new" "$channel_old"
mkdir "$channel_new"
(
    cd "$channel_new"
    ln -s ../"$bundle_version"/{install,update}.sh .
)
assert_subshell

if [[ -d $channel_dir ]]; then
    mv "$channel_dir" "$channel_old"
fi
mv "$channel_new" "$channel_dir"

if [[ ! $dev_install ]]; then
    chgrp -R -P -h apache "$dest_bundle_root"
fi

echo "Created: $dest"
