#!/bin/bash
# Copyright (c) 2015 RadiaSoft LLC.  All Rights Reserved.
#
# Build and run RadTrack bundle.
#
export dev_install=1
export dmg_src=$PWD/dmg

shopt -s nullglob
dmg_list=(dmg_src/*.dmg)
if (( ${#dmg_list[@]} < 3 )); then
    echo 'Not enough *.dmg in "dmg/*"' 1>&2
    exit 1
fi

dest=../bundle
export dest=$(cd "$dest"; pwd)
export repo=file://$dest

. ./bundle

curl -s "$repo/$bundle_name/$bundle_os_machine/$bundle_channel/install.sh" | bash -e
