#!/bin/bash
# Copyright (c) 2015 RadiaSoft LLC.  All Rights Reserved.
if [[ $bundle ]]; then
    no_container_build=1 ./bundler
fi
(curl -s -S -f "file://$PWD/../bundle/org.radtrack/darwin/x86_64/develop/install.sh" \
    || echo 'echo curl failed; exit 99') \
    | bash -e ${debug+-x}
