# Copyright (c) 2015 RadiaSoft LLC.  All Rights Reserved.
#
# Sets up the environment to run install-linux.sh
FROM fedora:21
MAINTAINER RadTrack <docker@radtrack.org>
ADD . /cfg
RUN sh /cfg/install-linux.sh
