#!/bin/bash
#
# Promotes a version to the next channel
#
# TODO(robnagler) do version calculation to make sure not skipping channelap
#
umask 027

. "$(dirname $0)/install-functions.sh"

version_dir=$(cd "${version_dir-$PWD}"; pwd)
channel=${channel-develop}

version=$(basename $version_dir)
if ! [[ $version =~ ^[0-9]+\.[0-9]+$ && -r $version_dir/install.sh && $channel =~ ^(develop|alpha|beta|stable)$ ]]; then
    echo "Usage: version_dir=<dir [pwd]> channel=<develop|alpha|beta|stable [develop]> $0" 1>&2
    exit 1
fi

. "$version_dir/install-bootstrap-vars.sh"

export install_channel=$channel
export install_channel_url=$(dirname "$install_version_url")/$install_channel

channel_dir=$(dirname "$version_dir")/$channel
channel_new=$channel_dir.new
channel_old=$channel_dir.old

rm -rf "$channel_new" "$channel_old"
mkdir "$channel_new"
(
    set -e
    cd "$channel_new"
    for b in install.sh update.sh; do
        install_template "$version_dir/$b" "$b"
    done
    group=$(install_group_from_file "$version_dir")
    chgrp -R "$group" .
)
assert_subshell

if [[ -d $channel_dir ]]; then
    mv "$channel_dir" "$channel_old"
fi
mv "$channel_new" "$channel_dir"

echo "Promoted: $version to $channel"
