#!/bin/bash
#
# Builds a Docker or Vagrant container running RadTrack
#
set -e
build_box=radiasoft/radtrack
build_base_docker=radiasoft/fedora
build_base_vagrant=$build_base_docker

. ../../radiasoft/fedora-container/libexec/build.sh
